### ISSUE TITLE
Improve docs of `EarlyStoppingCallback`

### ISSUE THREAD

**Issue by dpaetzel** [xcsf-dev/xcsf#120]
I wasn't sure whether I'm allowed to edit the wiki (which is maybe a bit too short in explaining the exact semantics of the new callback mechanism) and also wanted to check whether I got this right (since I'm only interested in supervised learning right now, this is not as abstract as it could be, sorry):

- Callbacks are called every `PERF_TRIALS` trials (let's call this an epoch). E.g. up to `MAX_TRIALS/PERF_TRIALS` times (if this is an integer, otherwise appropriately rounded).
- The `EarlyStoppingCallback` checks either a training or a validation data metric as given by its `monitor` parameter (e.g. `"train"`).
- Which kind of metric `EarlyStoppingCallback` checks depends on `loss_func` (metric computation is done in `xcs_supervised_fit`) since the metric value is the mean `loss_func` value on the (train or validation) data during the `PERF_TRIALS` performed (i.e. during the epoch).
- The `patience` parameter to `EarlyStoppingCallback` is measured at the trial level and not at the epoch level.

If I got this correct, I can edit the wiki accordingly, if you want. Or maybe just link to this issue for now?

**Comment by rpreen** [comment]
That's correct, although the last point is not quite right: callbacks are executed after each "epoch" (`perf_trials`) of learning, so the `patience` parameter is checked at that point. So `patience` should be a multiple of `perf_trials` since there's no point using smaller numbers - probably it should be an "epoch" parameter to be clearer, but there are too many parameters already and I think it's easier to understand the link if it's measured in trials since it is doing one sample/trial at a time learning even though the data is supplied in batch.

Be great if you could update the wiki.

**Comment by dpaetzel** [comment]
OK, that's actually exactly what I meant: I guess I should rephrase it in the wiki to the _unit_ of `patience` being _trials_ (but the whole `EarlyStoppingCondition` being fulfilled is only ever checked every _epoch_).

I'll still have to check how this interacts with Reinforcement Learning (probably just the same?) but then I'll be happy to update the wiki. :+1:

**Comment by rpreen** [comment]
I don't think it matters for RL because the RL-specific functions don't use callbacks; and if using the supervised `fit()` method, it's probably best to do one sample at a time (with `max_trials=1` and `warm_start=True`)  like in the cartpole example to keep the temporal difference calculation in Python and therefore you wouldn't use callbacks there - deciding whether it's fit enough is a decision to be made in Python.

**Comment by rpreen** [comment]
I've updated the wiki so will close this issue. Feel free to add or tweak anything to make it clearer.

**Comment by dpaetzel** [comment]
Thank you and sorry that I didn't manage to find time to do this myself in the last weeks :see_no_evil:
