### ISSUE TITLE
`XCS().get_params()` does not contain the action config

### ISSUE THREAD

**Issue by dpaetzel** [xcsf-dev/xcsf#95]
First of all: Thank you for adding the sklearn interface! This helps a lot! :slightly_smiling_face: 

I just noticed that `XCS().get_params()` returns

```
{'version': '1.3.1', 'x_dim': 1, 'y_dim': 1, 'n_actions': 1, 'omp_num_threads': 8, 'random_state': 0, 'population_file': '', 'pop_init': True, 'max_trials': 100000, 'perf_trials': 1000, 'pop_size': 2000, 'loss_func': 'mae', 'set_subsumption': False, 'theta_sub': 100, 'e0': 0.01, 'alpha': 0.1, 'nu': 5, 'beta': 0.1, 'delta': 0.1, 'theta_del': 20, 'init_fitness': 0.01, 'init_error': 0, 'm_probation': 10000, 'stateful': True, 'compaction': False, 'ea': {'select_type': 'roulette', 'theta_ea': 50, 'lambda': 2, 'p_crossover': 0.8, 'err_reduc': 1, 'fit_reduc': 0.1, 'subsumption': False, 'pred_reset': False}, 'condition': {'type': 'hyperrectangle_csr', 'args': {'eta': 0, 'min': 0, 'max': 1, 'spread_min': 0.1}}, 'prediction': {'type': 'nlms_linear', 'args': {'x0': 1, 'eta': 0.1, 'evolve_eta': True, 'eta_min': 1e-05}}}
```

which does not include the `action` dictionary. I'd expect

```
XCS().get_params()["action"]
```

to return a dict (the default which is probably `{"type": "integer"}`?) but it throws a `KeyError`.

Interestingly, this works:

```
xcsf.XCS(action={"type" : "integer"}).get_params()["action"]
```

and returns correctly `{"type" : "integer"}`.

**Comment by rpreen** [comment]
This is because in order to make it sklearn compatible I had to introduce two methods to get the parameters:

* `get_params()` returns a dictionary containing the "external" parameters - that is the ones specified in the calling Python script; so for example, setting `x_dim=2` will be added to this dictionary when calling the constructor or using `set_params()` and then `get_params()` will return this dictionary - this means that the memory addresses for the value "2" match -- and is required by sklearn; however internally the `kwargs` are converted into JSON and then parsed through the library (the benefit of this is that parameters internally only need to be handled once and it works for both the stand-alone binary as well as Python and it simplifies the process of adding parameters because there are so many of them, so they don't need to be individually defined in the constructor - the constructor just takes `kwargs`;
* `internal_params()` will return ALL of the parameters actually used internally - **this is what you probably want**

I'll add some notes to the wiki to make it a bit clearer

**Comment by rpreen** [comment]
I'll try something later to see if I can get around this hack, which I never really liked but it does make sklearn happy.

**Comment by dpaetzel** [comment]
Ah, I see, thank you for the clarification! (Also, I remember faintly that you posted something along those lines already as a response to another issue …)

**Comment by dpaetzel** [comment]
However, `internal_params()` doesn't contain the `action` dict either since

```
xcsf.XCS().internal_params() == xcsf.XCS().get_params()
True
```

**Comment by rpreen** [comment]
I think if you are doing supervised learning then it automatically hides the action details from parameters and also when getting the population since there isn't really an action being used it seemed cleaner - I think it shouldn't actually even matter any more what action type you specify if `y_dim=1` then it infers there is no action set.

**Comment by dpaetzel** [comment]
While I agree that `n_actions=1` implies a certain `action=…`, XCS has already so many parameters that I myself would choose explicitness here over some intelligent heuristic as to which parameters are shown.

As an aside: Why does `XCS().get_params()` even return any parameters? `XCS()` does not specify any … Or what do you mean by

> the [parameters] specified in the calling Python script[?]

**Comment by rpreen** [comment]
Sorry that was a bit misleading, what happens currently is this:

`__init__()`

1) constructor sets parameter values to defaults internally (including `x_dim=1, y_dim=1, n_actions=1`); 
2) these internal parameters exported from JSON and used to update an exposed `params` dict;
3) if any `kwargs` specified, `set_params()` automatically called (see below);


`set_params()`

1) `kwargs` imported internally via JSON;
2) `params` dict updated directly with the `kwargs` (no JSON export);


`get_params()`

1) returns the exposed `params` dict


`internal_params()`

1) returns exported internal parameters from JSON as a dict


----

`get_params()` and `internal_params()` can be different because when importing the params via JSON some extra validation checks are performed and parameters added for example for neural networks, it automatically computes the number of inputs for each layer; so when exporting it back (as with `internal_params()` these will show up but wont for `get_params()`

It's kind of a messy solution, but like I said it's to maintain the memory addresses for the dicts used in `set_params()` and `get_params()` and while the actual values are obviously the same internally, when they are exported via JSON the memory addresses wont be the same

**Comment by rpreen** [comment]
So the reason for your difference is just because of the hiding that I mentioned before because `n_actions=1`  -- and I think the only difference between `get_params()` and `internal_params()` really arises when using neural nets because it has to do extra validation on the parameters and compute things like the number of inputs.

I can unhide the `action` dictionary for the parameters when `n_actions=1` but I do wonder if that just adds clutter since there are no actions in that setting. That parameter is more than just a heuristic really because it's the fundamental flag to switch between supervised and RL modes and the consequent action set building and prediction array updating etc.

**Comment by rpreen** [comment]
Other parameters that are hidden when `n_actions=1` are other RL parameters like `gamma` and `teletransportation`. The actions are also hidden when using a "rule" condition, e.g., a neural network that performs both the matching and action functionality in a single network - so it would display the separate action component parameters even though it wasn't used and might be misleading...

https://github.com/xcsf-dev/xcsf/blob/ab835aa1418e6463a175d8cc96862b0ab3764015/xcsf/param.c#L107-L184

**Comment by dpaetzel** [comment]
Thank you for the clarification. I don't think that anything needs to be changed then; also, the design decision you made there seems entirely reasonable to me.
